using Microsoft.VisualStudio.Language.Intellisense;
using Microsoft.VisualStudio.Text;
using Microsoft.VisualStudio.Text.Operations;
using System;
using System.Collections.Generic;

namespace ILSupport.Intellisense
{
    internal class LanguageCompletionSource : ICompletionSource
    {
        private LanguageCompletionSourceProvider m_sourceProvider;
        private ITextBuffer m_textBuffer;
        private List<Completion> m_compList;

        public LanguageCompletionSource(LanguageCompletionSourceProvider sourceProvider, ITextBuffer textBuffer)
        {
            m_sourceProvider = sourceProvider;
            m_textBuffer = textBuffer;
        }

        void ICompletionSource.AugmentCompletionSession(ICompletionSession session, IList<CompletionSet> completionSets)
        {
            completionSets.Add(new CompletionSet(
                "Tokens",    //the non-localized title of the tab 
                "Tokens",    //the display title of the tab
                FindTokenSpanAtPosition(session.GetTriggerPoint(m_textBuffer),
                    session),
                CompletionList,
                null));
        }

        private ITrackingSpan FindTokenSpanAtPosition(ITrackingPoint point, ICompletionSession session)
        {
            SnapshotPoint currentPoint = (session.TextView.Caret.Position.BufferPosition) - 1;
            ITextStructureNavigator navigator = m_sourceProvider.NavigatorService.GetTextStructureNavigator(m_textBuffer);
            TextExtent extent = navigator.GetExtentOfWord(currentPoint);
            return currentPoint.Snapshot.CreateTrackingSpan(extent.Span, SpanTrackingMode.EdgeInclusive);
        }

        private bool m_isDisposed;
        public void Dispose()
        {
            if (!m_isDisposed)
            {
                GC.SuppressFinalize(this);
                m_isDisposed = true;
            }
        }

        public static IEnumerable<Completion> CompletionList = new List<Completion>()
            {
                new Completion("nop", "nop",
                    @"Fills space if opcodes are patched. No meaningful operation is performed although a processing cycle can be consumed.",
                    null, "nop"),
                new Completion("break", "break",
                    @"Signals the Common Language Infrastructure (CLI) to inform the debugger that a break point has been tripped.",
                    null, "break"),
                new Completion("ldarg.0", "ldarg.0", @"Loads the argument at index 0 onto the evaluation stack.", null,
                    "ldarg.0"),
                new Completion("ldarg.1", "ldarg.1", @"Loads the argument at index 1 onto the evaluation stack.", null,
                    "ldarg.1"),
                new Completion("ldarg.2", "ldarg.2", @"Loads the argument at index 2 onto the evaluation stack.", null,
                    "ldarg.2"),
                new Completion("ldarg.3", "ldarg.3", @"Loads the argument at index 3 onto the evaluation stack.", null,
                    "ldarg.3"),
                new Completion("ldloc.0", "ldloc.0", @"Loads the local variable at index 0 onto the evaluation stack.",
                    null, "ldloc.0"),
                new Completion("ldloc.1", "ldloc.1", @"Loads the local variable at index 1 onto the evaluation stack.",
                    null, "ldloc.1"),
                new Completion("ldloc.2", "ldloc.2", @"Loads the local variable at index 2 onto the evaluation stack.",
                    null, "ldloc.2"),
                new Completion("ldloc.3", "ldloc.3", @"Loads the local variable at index 3 onto the evaluation stack.",
                    null, "ldloc.3"),
                new Completion("stloc.0", "stloc.0",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 0.",
                    null, "stloc.0"),
                new Completion("stloc.1", "stloc.1",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 1.",
                    null, "stloc.1"),
                new Completion("stloc.2", "stloc.2",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 2.",
                    null, "stloc.2"),
                new Completion("stloc.3", "stloc.3",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index 3.",
                    null, "stloc.3"),
                new Completion("ldarg.s", "ldarg.s",
                    @"Loads the argument (referenced by a specified short form index) onto the evaluation stack.", null,
                    "ldarg.s"),
                new Completion("ldarga.s", "ldarga.s",
                    @"Load an argument address, in short form, onto the evaluation stack.", null, "ldarga.s"),
                new Completion("starg.s", "starg.s",
                    @"Stores the value on top of the evaluation stack in the argument slot at a specified index, short form.",
                    null, "starg.s"),
                new Completion("ldloc.s", "ldloc.s",
                    @"Loads the local variable at a specific index onto the evaluation stack, short form.", null,
                    "ldloc.s"),
                new Completion("ldloca.s", "ldloca.s",
                    @"Loads the address of the local variable at a specific index onto the evaluation stack, short form.",
                    null, "ldloca.s"),
                new Completion("stloc.s", "stloc.s",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at index (short form).",
                    null, "stloc.s"),
                new Completion("ldnull", "ldnull", @"Pushes a null reference (type O) onto the evaluation stack.", null,
                    "ldnull"),
                new Completion("ldc.i4.m1", "ldc.i4.m1",
                    @"Pushes the integer value of -1 onto the evaluation stack as an int32.", null, "ldc.i4.m1"),
                new Completion("ldc.i4.0", "ldc.i4.0",
                    @"Pushes the integer value of 0 onto the evaluation stack as an int32.", null, "ldc.i4.0"),
                new Completion("ldc.i4.1", "ldc.i4.1",
                    @"Pushes the integer value of 1 onto the evaluation stack as an int32.", null, "ldc.i4.1"),
                new Completion("ldc.i4.2", "ldc.i4.2",
                    @"Pushes the integer value of 2 onto the evaluation stack as an int32.", null, "ldc.i4.2"),
                new Completion("ldc.i4.3", "ldc.i4.3",
                    @"Pushes the integer value of 3 onto the evaluation stack as an int32.", null, "ldc.i4.3"),
                new Completion("ldc.i4.4", "ldc.i4.4",
                    @"Pushes the integer value of 4 onto the evaluation stack as an int32.", null, "ldc.i4.4"),
                new Completion("ldc.i4.5", "ldc.i4.5",
                    @"Pushes the integer value of 5 onto the evaluation stack as an int32.", null, "ldc.i4.5"),
                new Completion("ldc.i4.6", "ldc.i4.6",
                    @"Pushes the integer value of 6 onto the evaluation stack as an int32.", null, "ldc.i4.6"),
                new Completion("ldc.i4.7", "ldc.i4.7",
                    @"Pushes the integer value of 7 onto the evaluation stack as an int32.", null, "ldc.i4.7"),
                new Completion("ldc.i4.8", "ldc.i4.8",
                    @"Pushes the integer value of 8 onto the evaluation stack as an int32.", null, "ldc.i4.8"),
                new Completion("ldc.i4.s", "ldc.i4.s",
                    @"Pushes the supplied int8 value onto the evaluation stack as an int32, short form.", null,
                    "ldc.i4.s"),
                new Completion("ldc.i4", "ldc.i4",
                    @"Pushes a supplied value of type int32 onto the evaluation stack as an int32.", null, "ldc.i4"),
                new Completion("ldc.i8", "ldc.i8",
                    @"Pushes a supplied value of type int64 onto the evaluation stack as an int64.", null, "ldc.i8"),
                new Completion("ldc.r4", "ldc.r4",
                    @"Pushes a supplied value of type float32 onto the evaluation stack as type F (float).", null,
                    "ldc.r4"),
                new Completion("ldc.r8", "ldc.r8",
                    @"Pushes a supplied value of type float64 onto the evaluation stack as type F (float).", null,
                    "ldc.r8"),
                new Completion("dup", "dup",
                    @"Copies the current topmost value on the evaluation stack, and then pushes the copy onto the evaluation stack.",
                    null, "dup"),
                new Completion("pop", "pop", @"Removes the value currently on top of the evaluation stack.", null, "pop"),
                new Completion("jmp", "jmp", @"Exits current method and jumps to specified method.", null, "jmp"),
                new Completion("call", "call", @"Calls the method indicated by the passed method descriptor.", null,
                    "call"),
                new Completion("calli", "calli",
                    @"Calls the method indicated on the evaluation stack (as a pointer to an entry point) with arguments described by a calling convention.",
                    null, "calli"),
                new Completion("ret", "ret",
                    @"Returns from the current method, pushing a return value (if present) from the callee's evaluation stack onto the caller's evaluation stack.",
                    null, "ret"),
                new Completion("br.s", "br.s",
                    @"Unconditionally transfers control to a target instruction (short form).", null, "br.s"),
                new Completion("brfalse.s", "brfalse.s",
                    @"Transfers control to a target instruction if value is false, a null reference, or zero.", null,
                    "brfalse.s"),
                new Completion("brtrue.s", "brtrue.s",
                    @"Transfers control to a target instruction (short form) if value is true, not null, or non-zero.",
                    null, "brtrue.s"),
                new Completion("beq.s", "beq.s",
                    @"Transfers control to a target instruction (short form) if two values are equal.", null, "beq.s"),
                new Completion("bge.s", "bge.s",
                    @"Transfers control to a target instruction (short form) if the first value is greater than or equal to the second value.",
                    null, "bge.s"),
                new Completion("bgt.s", "bgt.s",
                    @"Transfers control to a target instruction (short form) if the first value is greater than the second value.",
                    null, "bgt.s"),
                new Completion("ble.s", "ble.s",
                    @"Transfers control to a target instruction (short form) if the first value is less than or equal to the second value.",
                    null, "ble.s"),
                new Completion("blt.s", "blt.s",
                    @"Transfers control to a target instruction (short form) if the first value is less than the second value.",
                    null, "blt.s"),
                new Completion("bne.un.s", "bne.un.s",
                    @"Transfers control to a target instruction (short form) when two unsigned integer values or unordered float values are not equal.",
                    null, "bne.un.s"),
                new Completion("bge.un.s", "bge.un.s",
                    @"Transfers control to a target instruction (short form) if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "bge.un.s"),
                new Completion("bgt.un.s", "bgt.un.s",
                    @"Transfers control to a target instruction (short form) if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "bgt.un.s"),
                new Completion("ble.un.s", "ble.un.s",
                    @"Transfers control to a target instruction (short form) if the first value is less than or equal to the second value, when comparing unsigned integer values or unordered float values.",
                    null, "ble.un.s"),
                new Completion("blt.un.s", "blt.un.s",
                    @"Transfers control to a target instruction (short form) if the first value is less than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "blt.un.s"),
                new Completion("br", "br", @"Unconditionally transfers control to a target instruction.", null, "br"),
                new Completion("brfalse", "brfalse",
                    @"Transfers control to a target instruction if value is false, a null reference (Nothing in Visual Basic), or zero.",
                    null, "brfalse"),
                new Completion("brtrue", "brtrue",
                    @"Transfers control to a target instruction if value is true, not null, or non-zero.", null,
                    "brtrue"),
                new Completion("beq", "beq", @"Transfers control to a target instruction if two values are equal.", null,
                    "beq"),
                new Completion("bge", "bge",
                    @"Transfers control to a target instruction if the first value is greater than or equal to the second value.",
                    null, "bge"),
                new Completion("bgt", "bgt",
                    @"Transfers control to a target instruction if the first value is greater than the second value.",
                    null, "bgt"),
                new Completion("ble", "ble",
                    @"Transfers control to a target instruction if the first value is less than or equal to the second value.",
                    null, "ble"),
                new Completion("blt", "blt",
                    @"Transfers control to a target instruction if the first value is less than the second value.", null,
                    "blt"),
                new Completion("bne.un", "bne.un",
                    @"Transfers control to a target instruction when two unsigned integer values or unordered float values are not equal.",
                    null, "bne.un"),
                new Completion("bge.un", "bge.un",
                    @"Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "bge.un"),
                new Completion("bgt.un", "bgt.un",
                    @"Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "bgt.un"),
                new Completion("ble.un", "ble.un",
                    @"Transfers control to a target instruction if the first value is less than or equal to the second value, when comparing unsigned integer values or unordered float values.",
                    null, "ble.un"),
                new Completion("blt.un", "blt.un",
                    @"Transfers control to a target instruction if the first value is less than the second value, when comparing unsigned integer values or unordered float values.",
                    null, "blt.un"),
                new Completion("switch", "switch", @"Implements a jump table.", null, "switch"),
                new Completion("ldind.i1", "ldind.i1",
                    @"Loads a value of type int8 as an int32 onto the evaluation stack indirectly.", null, "ldind.i1"),
                new Completion("ldind.u1", "ldind.u1",
                    @"Loads a value of type unsigned int8 as an int32 onto the evaluation stack indirectly.", null,
                    "ldind.u1"),
                new Completion("ldind.i2", "ldind.i2",
                    @"Loads a value of type int16 as an int32 onto the evaluation stack indirectly.", null, "ldind.i2"),
                new Completion("ldind.u2", "ldind.u2",
                    @"Loads a value of type unsigned int16 as an int32 onto the evaluation stack indirectly.", null,
                    "ldind.u2"),
                new Completion("ldind.i4", "ldind.i4",
                    @"Loads a value of type int32 as an int32 onto the evaluation stack indirectly.", null, "ldind.i4"),
                new Completion("ldind.u4", "ldind.u4",
                    @"Loads a value of type unsigned int32 as an int32 onto the evaluation stack indirectly.", null,
                    "ldind.u4"),
                new Completion("ldind.i8", "ldind.i8",
                    @"Loads a value of type int64 as an int64 onto the evaluation stack indirectly.", null, "ldind.i8"),
                new Completion("ldind.i", "ldind.i",
                    @"Loads a value of type native int as a native int onto the evaluation stack indirectly.", null,
                    "ldind.i"),
                new Completion("ldind.r4", "ldind.r4",
                    @"Loads a value of type float32 as a type F (float) onto the evaluation stack indirectly.", null,
                    "ldind.r4"),
                new Completion("ldind.r8", "ldind.r8",
                    @"Loads a value of type float64 as a type F (float) onto the evaluation stack indirectly.", null,
                    "ldind.r8"),
                new Completion("ldind.ref", "ldind.ref",
                    @"Loads an object reference as a type O (object reference) onto the evaluation stack indirectly.",
                    null, "ldind.ref"),
                new Completion("stind.ref", "stind.ref", @"Stores a object reference value at a supplied address.", null,
                    "stind.ref"),
                new Completion("stind.i1", "stind.i1", @"Stores a value of type int8 at a supplied address.", null,
                    "stind.i1"),
                new Completion("stind.i2", "stind.i2", @"Stores a value of type int16 at a supplied address.", null,
                    "stind.i2"),
                new Completion("stind.i4", "stind.i4", @"Stores a value of type int32 at a supplied address.", null,
                    "stind.i4"),
                new Completion("stind.i8", "stind.i8", @"Stores a value of type int64 at a supplied address.", null,
                    "stind.i8"),
                new Completion("stind.r4", "stind.r4", @"Stores a value of type float32 at a supplied address.", null,
                    "stind.r4"),
                new Completion("stind.r8", "stind.r8", @"Stores a value of type float64 at a supplied address.", null,
                    "stind.r8"),
                new Completion("add", "add", @"Adds two values and pushes the result onto the evaluation stack.", null,
                    "add"),
                new Completion("sub", "sub",
                    @"Subtracts one value from another and pushes the result onto the evaluation stack.", null, "sub"),
                new Completion("mul", "mul", @"Multiplies two values and pushes the result on the evaluation stack.",
                    null, "mul"),
                new Completion("div", "div",
                    @"Divides two values and pushes the result as a floating-point (type F) or quotient (type int32) onto the evaluation stack.",
                    null, "div"),
                new Completion("div.un", "div.un",
                    @"Divides two unsigned integer values and pushes the result (int32) onto the evaluation stack.",
                    null, "div.un"),
                new Completion("rem", "rem", @"Divides two values and pushes the remainder onto the evaluation stack.",
                    null, "rem"),
                new Completion("rem.un", "rem.un",
                    @"Divides two unsigned values and pushes the remainder onto the evaluation stack.", null, "rem.un"),
                new Completion("and", "and",
                    @"Computes the bitwise AND of two values and pushes the result onto the evaluation stack.", null,
                    "and"),
                new Completion("or", "or",
                    @"Compute the bitwise complement of the two integer values on top of the stack and pushes the result onto the evaluation stack.",
                    null, "or"),
                new Completion("xor", "xor",
                    @"Computes the bitwise XOR of the top two values on the evaluation stack, pushing the result onto the evaluation stack.",
                    null, "xor"),
                new Completion("shl", "shl",
                    @"Shifts an integer value to the left (in zeroes) by a specified number of bits, pushing the result onto the evaluation stack.",
                    null, "shl"),
                new Completion("shr", "shr",
                    @"Shifts an integer value (in sign) to the right by a specified number of bits, pushing the result onto the evaluation stack.",
                    null, "shr"),
                new Completion("shr.un", "shr.un",
                    @"Shifts an unsigned integer value (in zeroes) to the right by a specified number of bits, pushing the result onto the evaluation stack.",
                    null, "shr.un"),
                new Completion("neg", "neg", @"Negates a value and pushes the result onto the evaluation stack.", null,
                    "neg"),
                new Completion("not", "not",
                    @"Computes the bitwise complement of the integer value on top of the stack and pushes the result onto the evaluation stack as the same type.",
                    null, "not"),
                new Completion("conv.i1", "conv.i1",
                    @"Converts the value on top of the evaluation stack to int8, then extends (pads) it to int32.", null,
                    "conv.i1"),
                new Completion("conv.i2", "conv.i2",
                    @"Converts the value on top of the evaluation stack to int16, then extends (pads) it to int32.",
                    null, "conv.i2"),
                new Completion("conv.i4", "conv.i4", @"Converts the value on top of the evaluation stack to int32.",
                    null, "conv.i4"),
                new Completion("conv.i8", "conv.i8", @"Converts the value on top of the evaluation stack to int64.",
                    null, "conv.i8"),
                new Completion("conv.r4", "conv.r4", @"Converts the value on top of the evaluation stack to float32.",
                    null, "conv.r4"),
                new Completion("conv.r8", "conv.r8", @"Converts the value on top of the evaluation stack to float64.",
                    null, "conv.r8"),
                new Completion("conv.u4", "conv.u4",
                    @"Converts the value on top of the evaluation stack to unsigned int32, and extends it to int32.",
                    null, "conv.u4"),
                new Completion("conv.u8", "conv.u8",
                    @"Converts the value on top of the evaluation stack to unsigned int64, and extends it to int64.",
                    null, "conv.u8"),
                new Completion("callvirt", "callvirt",
                    @"Calls a late-bound method on an object, pushing the return value onto the evaluation stack.", null,
                    "callvirt"),
                new Completion("cpobj", "cpobj",
                    @"Copies the value type located at the address of an object (type &, * or native int) to the address of the destination object (type &, * or native int).",
                    null, "cpobj"),
                new Completion("ldobj", "ldobj",
                    @"Copies the value type object pointed to by an address to the top of the evaluation stack.", null,
                    "ldobj"),
                new Completion("ldstr", "ldstr",
                    @"Pushes a new object reference to a string literal stored in the metadata.", null, "ldstr"),
                new Completion("newobj", "newobj",
                    @"Creates a new object or a new instance of a value type, pushing an object reference (type O) onto the evaluation stack.",
                    null, "newobj"),
                new Completion("castclass", "castclass",
                    @"Attempts to cast an object passed by reference to the specified class.", null, "castclass"),
                new Completion("isinst", "isinst",
                    @"Tests whether an object reference (type O) is an instance of a particular class.", null, "isinst"),
                new Completion("conv.r.un", "conv.r.un",
                    @"Converts the unsigned integer value on top of the evaluation stack to float32.", null, "conv.r.un"),
                new Completion("unbox", "unbox",
                    @"Converts the boxed representation of a value type to its unboxed form.", null, "unbox"),
                new Completion("throw", "throw", @"Throws the exception object currently on the evaluation stack.", null,
                    "throw"),
                new Completion("ldfld", "ldfld",
                    @"Finds the value of a field in the object whose reference is currently on the evaluation stack.",
                    null, "ldfld"),
                new Completion("ldflda", "ldflda",
                    @"Finds the address of a field in the object whose reference is currently on the evaluation stack.",
                    null, "ldflda"),
                new Completion("stfld", "stfld",
                    @"Replaces the value stored in the field of an object reference or pointer with a new value.", null,
                    "stfld"),
                new Completion("ldsfld", "ldsfld", @"Pushes the value of a static field onto the evaluation stack.",
                    null, "ldsfld"),
                new Completion("ldsflda", "ldsflda", @"Pushes the address of a static field onto the evaluation stack.",
                    null, "ldsflda"),
                new Completion("stsfld", "stsfld",
                    @"Replaces the value of a static field with a value from the evaluation stack.", null, "stsfld"),
                new Completion("stobj", "stobj",
                    @"Copies a value of a specified type from the evaluation stack into a supplied memory address.",
                    null, "stobj"),
                new Completion("conv.ovf.i1.un", "conv.ovf.i1.un",
                    @"Converts the unsigned value on top of the evaluation stack to signed int8 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i1.un"),
                new Completion("conv.ovf.i2.un", "conv.ovf.i2.un",
                    @"Converts the unsigned value on top of the evaluation stack to signed int16 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i2.un"),
                new Completion("conv.ovf.i4.un", "conv.ovf.i4.un",
                    @"Converts the unsigned value on top of the evaluation stack to signed int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i4.un"),
                new Completion("conv.ovf.i8.un", "conv.ovf.i8.un",
                    @"Converts the unsigned value on top of the evaluation stack to signed int64, throwing OverflowException on overflow.",
                    null, "conv.ovf.i8.un"),
                new Completion("conv.ovf.u1.un", "conv.ovf.u1.un",
                    @"Converts the unsigned value on top of the evaluation stack to unsigned int8 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u1.un"),
                new Completion("conv.ovf.u2.un", "conv.ovf.u2.un",
                    @"Converts the unsigned value on top of the evaluation stack to unsigned int16 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u2.un"),
                new Completion("conv.ovf.u4.un", "conv.ovf.u4.un",
                    @"Converts the unsigned value on top of the evaluation stack to unsigned int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u4.un"),
                new Completion("conv.ovf.u8.un", "conv.ovf.u8.un",
                    @"Converts the unsigned value on top of the evaluation stack to unsigned int64, throwing OverflowException on overflow.",
                    null, "conv.ovf.u8.un"),
                new Completion("conv.ovf.i.un", "conv.ovf.i.un",
                    @"Converts the unsigned value on top of the evaluation stack to signed native int, throwing OverflowException on overflow.",
                    null, "conv.ovf.i.un"),
                new Completion("conv.ovf.u.un", "conv.ovf.u.un",
                    @"Converts the unsigned value on top of the evaluation stack to unsigned native int, throwing OverflowException on overflow.",
                    null, "conv.ovf.u.un"),
                new Completion("box", "box", @"Converts a value type to an object reference (type O).", null, "box"),
                new Completion("newarr", "newarr",
                    @"Pushes an object reference to a new zero-based, one-dimensional array whose elements are of a specific type onto the evaluation stack.",
                    null, "newarr"),
                new Completion("ldlen", "ldlen",
                    @"Pushes the number of elements of a zero-based, one-dimensional array onto the evaluation stack.",
                    null, "ldlen"),
                new Completion("ldelema", "ldelema",
                    @"Loads the address of the array element at a specified array index onto the top of the evaluation stack as type & (managed pointer).",
                    null, "ldelema"),
                new Completion("ldelem.i1", "ldelem.i1",
                    @"Loads the element with type int8 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.i1"),
                new Completion("ldelem.u1", "ldelem.u1",
                    @"Loads the element with type unsigned int8 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.u1"),
                new Completion("ldelem.i2", "ldelem.i2",
                    @"Loads the element with type int16 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.i2"),
                new Completion("ldelem.u2", "ldelem.u2",
                    @"Loads the element with type unsigned int16 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.u2"),
                new Completion("ldelem.i4", "ldelem.i4",
                    @"Loads the element with type int32 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.i4"),
                new Completion("ldelem.u4", "ldelem.u4",
                    @"Loads the element with type unsigned int32 at a specified array index onto the top of the evaluation stack as an int32.",
                    null, "ldelem.u4"),
                new Completion("ldelem.i8", "ldelem.i8",
                    @"Loads the element with type int64 at a specified array index onto the top of the evaluation stack as an int64.",
                    null, "ldelem.i8"),
                new Completion("ldelem.i", "ldelem.i",
                    @"Loads the element with type native int at a specified array index onto the top of the evaluation stack as a native int.",
                    null, "ldelem.i"),
                new Completion("ldelem.r4", "ldelem.r4",
                    @"Loads the element with type float32 at a specified array index onto the top of the evaluation stack as type F (float).",
                    null, "ldelem.r4"),
                new Completion("ldelem.r8", "ldelem.r8",
                    @"Loads the element with type float64 at a specified array index onto the top of the evaluation stack as type F (float).",
                    null, "ldelem.r8"),
                new Completion("ldelem.ref", "ldelem.ref",
                    @"Loads the element containing an object reference at a specified array index onto the top of the evaluation stack as type O (object reference).",
                    null, "ldelem.ref"),
                new Completion("stelem.i", "stelem.i",
                    @"Replaces the array element at a given index with the native int value on the evaluation stack.",
                    null, "stelem.i"),
                new Completion("stelem.i1", "stelem.i1",
                    @"Replaces the array element at a given index with the int8 value on the evaluation stack.", null,
                    "stelem.i1"),
                new Completion("stelem.i2", "stelem.i2",
                    @"Replaces the array element at a given index with the int16 value on the evaluation stack.", null,
                    "stelem.i2"),
                new Completion("stelem.i4", "stelem.i4",
                    @"Replaces the array element at a given index with the int32 value on the evaluation stack.", null,
                    "stelem.i4"),
                new Completion("stelem.i8", "stelem.i8",
                    @"Replaces the array element at a given index with the int64 value on the evaluation stack.", null,
                    "stelem.i8"),
                new Completion("stelem.r4", "stelem.r4",
                    @"Replaces the array element at a given index with the float32 value on the evaluation stack.", null,
                    "stelem.r4"),
                new Completion("stelem.r8", "stelem.r8",
                    @"Replaces the array element at a given index with the float64 value on the evaluation stack.", null,
                    "stelem.r8"),
                new Completion("stelem.ref", "stelem.ref",
                    @"Replaces the array element at a given index with the object ref value (type O) on the evaluation stack.",
                    null, "stelem.ref"),
                new Completion("ldelem", "ldelem",
                    @"Loads the element at a specified array index onto the top of the evaluation stack as the type specified in the instruction.",
                    null, "ldelem"),
                new Completion("stelem", "stelem",
                    @"Replaces the array element at a given index with the value on the evaluation stack, whose type is specified in the instruction.",
                    null, "stelem"),
                new Completion("unbox.any", "unbox.any",
                    @"Converts the boxed representation of a type specified in the instruction to its unboxed form.",
                    null, "unbox.any"),
                new Completion("conv.ovf.i1", "conv.ovf.i1",
                    @"Converts the signed value on top of the evaluation stack to signed int8 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i1"),
                new Completion("conv.ovf.u1", "conv.ovf.u1",
                    @"Converts the signed value on top of the evaluation stack to unsigned int8 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u1"),
                new Completion("conv.ovf.i2", "conv.ovf.i2",
                    @"Converts the signed value on top of the evaluation stack to signed int16 and extending it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i2"),
                new Completion("conv.ovf.u2", "conv.ovf.u2",
                    @"Converts the signed value on top of the evaluation stack to unsigned int16 and extends it to int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u2"),
                new Completion("conv.ovf.i4", "conv.ovf.i4",
                    @"Converts the signed value on top of the evaluation stack to signed int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.i4"),
                new Completion("conv.ovf.u4", "conv.ovf.u4",
                    @"Converts the signed value on top of the evaluation stack to unsigned int32, throwing OverflowException on overflow.",
                    null, "conv.ovf.u4"),
                new Completion("conv.ovf.i8", "conv.ovf.i8",
                    @"Converts the signed value on top of the evaluation stack to signed int64, throwing OverflowException on overflow.",
                    null, "conv.ovf.i8"),
                new Completion("conv.ovf.u8", "conv.ovf.u8",
                    @"Converts the signed value on top of the evaluation stack to unsigned int64, throwing OverflowException on overflow.",
                    null, "conv.ovf.u8"),
                new Completion("refanyval", "refanyval",
                    @"Retrieves the address (type &) embedded in a typed reference.", null, "refanyval"),
                new Completion("ckfinite", "ckfinite", @"Throws ArithmeticException if value is not a finite number.",
                    null, "ckfinite"),
                new Completion("mkrefany", "mkrefany",
                    @"Pushes a typed reference to an instance of a specific type onto the evaluation stack.", null,
                    "mkrefany"),
                new Completion("ldtoken", "ldtoken",
                    @"Converts a metadata token to its runtime representation, pushing it onto the evaluation stack.",
                    null, "ldtoken"),
                new Completion("conv.u2", "conv.u2",
                    @"Converts the value on top of the evaluation stack to unsigned int16, and extends it to int32.",
                    null, "conv.u2"),
                new Completion("conv.u1", "conv.u1",
                    @"Converts the value on top of the evaluation stack to unsigned int8, and extends it to int32.",
                    null, "conv.u1"),
                new Completion("conv.i", "conv.i", @"Converts the value on top of the evaluation stack to native int.",
                    null, "conv.i"),
                new Completion("conv.ovf.i", "conv.ovf.i",
                    @"Converts the signed value on top of the evaluation stack to signed native int, throwing OverflowException on overflow.",
                    null, "conv.ovf.i"),
                new Completion("conv.ovf.u", "conv.ovf.u",
                    @"Converts the signed value on top of the evaluation stack to unsigned native int, throwing OverflowException on overflow.",
                    null, "conv.ovf.u"),
                new Completion("add.ovf", "add.ovf",
                    @"Adds two integers, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "add.ovf"),
                new Completion("add.ovf.un", "add.ovf.un",
                    @"Adds two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "add.ovf.un"),
                new Completion("mul.ovf", "mul.ovf",
                    @"Multiplies two integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "mul.ovf"),
                new Completion("mul.ovf.un", "mul.ovf.un",
                    @"Multiplies two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "mul.ovf.un"),
                new Completion("sub.ovf", "sub.ovf",
                    @"Subtracts one integer value from another, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "sub.ovf"),
                new Completion("sub.ovf.un", "sub.ovf.un",
                    @"Subtracts one unsigned integer value from another, performs an overflow check, and pushes the result onto the evaluation stack.",
                    null, "sub.ovf.un"),
                new Completion("endfinally", "endfinally",
                    @"Transfers control from the fault or finally clause of an exception block back to the Common Language Infrastructure (CLI) exception handler.",
                    null, "endfinally"),
                new Completion("leave", "leave",
                    @"Exits a protected region of code, unconditionally transferring control to a specific target instruction.",
                    null, "leave"),
                new Completion("leave.s", "leave.s",
                    @"Exits a protected region of code, unconditionally transferring control to a target instruction (short form).",
                    null, "leave.s"),
                new Completion("stind.i", "stind.i", @"Stores a value of type native int at a supplied address.", null,
                    "stind.i"),
                new Completion("conv.u", "conv.u",
                    @"Converts the value on top of the evaluation stack to unsigned native int, and extends it to native int.",
                    null, "conv.u"),
                new Completion("prefix7", "prefix7", @"This is a reserved instruction.", null, "prefix7"),
                new Completion("prefix6", "prefix6", @"This is a reserved instruction.", null, "prefix6"),
                new Completion("prefix5", "prefix5", @"This is a reserved instruction.", null, "prefix5"),
                new Completion("prefix4", "prefix4", @"This is a reserved instruction.", null, "prefix4"),
                new Completion("prefix3", "prefix3", @"This is a reserved instruction.", null, "prefix3"),
                new Completion("prefix2", "prefix2", @"This is a reserved instruction.", null, "prefix2"),
                new Completion("prefix1", "prefix1", @"This is a reserved instruction.", null, "prefix1"),
                new Completion("prefixref", "prefixref", @"This is a reserved instruction.", null, "prefixref"),
                new Completion("arglist", "arglist",
                    @"Returns an unmanaged pointer to the argument list of the current method.", null, "arglist"),
                new Completion("ceq", "ceq",
                    @"Compares two values. If they are equal, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
                    null, "ceq"),
                new Completion("cgt", "cgt",
                    @"Compares two values. If the first value is greater than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
                    null, "cgt"),
                new Completion("cgt.un", "cgt.un",
                    @"Compares two unsigned or unordered values. If the first value is greater than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
                    null, "cgt.un"),
                new Completion("clt", "clt",
                    @"Compares two values. If the first value is less than the second, the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
                    null, "clt"),
                new Completion("clt.un", "clt.un",
                    @"Compares the unsigned or unordered values value1 and value2. If value1 is less than value2, then the integer value 1 (int32) is pushed onto the evaluation stack; otherwise 0 (int32) is pushed onto the evaluation stack.",
                    null, "clt.un"),
                new Completion("ldftn", "ldftn",
                    @"Pushes an unmanaged pointer (type native int) to the native code implementing a specific method onto the evaluation stack.",
                    null, "ldftn"),
                new Completion("ldvirtftn", "ldvirtftn",
                    @"Pushes an unmanaged pointer (type native int) to the native code implementing a particular virtual method associated with a specified object onto the evaluation stack.",
                    null, "ldvirtftn"),
                new Completion("ldarg", "ldarg",
                    @"Loads an argument (referenced by a specified index value) onto the stack.", null, "ldarg"),
                new Completion("ldarga", "ldarga", @"Load an argument address onto the evaluation stack.", null,
                    "ldarga"),
                new Completion("starg", "starg",
                    @"Stores the value on top of the evaluation stack in the argument slot at a specified index.", null,
                    "starg"),
                new Completion("ldloc", "ldloc",
                    @"Loads the local variable at a specific index onto the evaluation stack.", null, "ldloc"),
                new Completion("ldloca", "ldloca",
                    @"Loads the address of the local variable at a specific index onto the evaluation stack.", null,
                    "ldloca"),
                new Completion("stloc", "stloc",
                    @"Pops the current value from the top of the evaluation stack and stores it in a the local variable list at a specified index.",
                    null, "stloc"),
                new Completion("localloc", "localloc",
                    @"Allocates a certain number of bytes from the local dynamic memory pool and pushes the address (a transient pointer, type *) of the first allocated byte onto the evaluation stack.",
                    null, "localloc"),
                new Completion("endfilter", "endfilter",
                    @"Transfers control from the filter clause of an exception back to the Common Language Infrastructure (CLI) exception handler.",
                    null, "endfilter"),
                new Completion("unaligned", "unaligned",
                    @"Indicates that an address currently atop the evaluation stack might not be aligned to the natural size of the immediately following ldind, stind, ldfld, stfld, ldobj, stobj, initblk, or cpblk instruction.",
                    null, "unaligned"),
                new Completion("volatile", "volatile",
                    @"Specifies that an address currently atop the evaluation stack might be volatile, and the results of reading that location cannot be cached or that multiple stores to that location cannot be suppressed.",
                    null, "volatile"),
                new Completion("tailcall", "tailcall",
                    @"Performs a postfixed method call instruction such that the current method's stack frame is removed before the actual call instruction is executed.",
                    null, "tailcall"),
                new Completion("initobj", "initobj",
                    @"Initializes each field of the value type at a specified address to a null reference or a 0 of the appropriate primitive type.",
                    null, "initobj"),
                new Completion("constrained", "constrained",
                    @"Constrains the type on which a virtual method call is made.", null, "constrained"),
                new Completion("cpblk", "cpblk",
                    @"Copies a specified number bytes from a source address to a destination address.", null, "cpblk"),
                new Completion("initblk", "initblk",
                    @"Initializes a specified block of memory at a specific address to a given size and initial value.",
                    null, "initblk"),
                new Completion("rethrow", "rethrow", @"Rethrows the current exception.", null, "rethrow"),
                new Completion("sizeof", "sizeof",
                    @"Pushes the size, in bytes, of a supplied value type onto the evaluation stack.", null, "sizeof"),
                new Completion("refanytype", "refanytype", @"Retrieves the type token embedded in a typed reference.",
                    null, "refanytype"),
                new Completion("readonly", "readonly",
                    @"Specifies that the subsequent array address operation performs no type check at run time, and that it returns a managed pointer whose mutability is restricted.",
                    null, "readonly")

            };

    }
}
